### PR TITLE
Add GitHub Actions CI

### LINKED ISSUE #68: "include" is deprecated
Ansible tell us that "include" is deprecated:
```
[DEPRECATION WARNING]: "include" is deprecated, use include_tasks/import_tasks instead...
```

There are a few includes that should be replace with "include_tasks":
```
tasks/install.yml
2:- include: install-Debian.yml
5:- include: install-Generic.yml

tasks/main.yml
14:- include: install.yml
18:- include: firewall.yml
22:- include: selinux.yml
26:- include: config.yml
29:- include: sysctl.yml
33:- include: docker.yml
```

Could you please fix them? Thanks!

### PR DESCRIPTION
**Pull request by haydenseitz**
## Changes

- Add Github Actions CI config
- Updates molecule to v5 syntax
- Removes lint from molecule tests
- Enable idempotency in molecule
- Improves yamllint config for ansible-lint
- Refreshed OS distros in molecule tests
- Fixes #68 
- Fixes ansible-lint violations

### CODE REVIEW

**Comment by haydenseitz** [comment]
Action job example: https://github.com/haydenseitz/ansible-haproxy/actions/runs/5205531754

**Comment by haydenseitz** [comment]
Removed distros for failing jobs (unsupported/deprecated docker images)

**Comment by goldyfruit** [comment]
Hi @haydenseitz 

Awesome work! :1st_place_medal: 

Maybe we could had more recent Fedora releases as well as EL 9? What do you think?

**Comment by haydenseitz** [comment]
Added updated Fedora and RockyLinux versions. I'm not sure about RHEL images, I do not believe there are any official ones on the Docker Hub, but if you or someone has an image they would like to use, you can link it and I will add.

**Comment by goldyfruit** [comment]
> Added updated Fedora and RockyLinux versions. I'm not sure about RHEL OS, I do not believe there are any official ones on the Docker Hub, but if you or someone has an image they would like to use, you can link it and I will add.

RockyLinux should be enough! Thanks for checking.

**Pull request merged**
