### PR TITLE
Split debian & generic installation to permit use Debian backports

### PR DESCRIPTION
**Pull request by nerzhul**

### CODE REVIEW

**Comment by goldyfruit** [comment]
@nerzhul thanks !

The options related to MySQL and PgSQL should not be declare like that.
_backend_ options should be declare like in that way:

```
haproxy_backend:
  - dashboard_backend:
      balance: source
  - options:
      mysql-check user
```

About `haproxy_apt_backports`, could you please turn it to `false` by default ?

**Comment by nerzhul** [comment]
@goldyfruit i updated the PR to remove the options to the generic backend and only add the Debian installation & reload handler

**Comment by goldyfruit** [comment]
@nerzhul thx !!

**Comment by nerzhul** [comment]
No problem, this is a good role :)

**Pull request merged**
