### PR TITLE
IMP support customization of package, service, config and binary path

### PR DESCRIPTION
**Pull request by Sturlik**
Currently one of way to install HaProxy LTS version on CentOS is to install via Software Collections.
But there's issues with package, service names and config and binary path.

This commit adds support for customizing:
- Package name. For Software Collections: rh-haproxy18
- Service name. In case of Software Collections: rh-haproxy18-haproxy
- Config file location. For Software Collections: /etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg
- Binnary path. Example: /opt/rh/rh-haproxy18/root/usr/sbin/haproxy

### CODE REVIEW

**Comment by goldyfruit** [comment]
@Sturlik could you please have a look why the molecule tests failed?
https://travis-ci.org/github/uoi-io/ansible-haproxy/jobs/686204009

**Comment by dsavineau** [comment]
I guess this is unrelated to the PR itself so I'll take a look tomorrow.

**Comment by goldyfruit** [comment]
> I guess this is unrelated to the PR itself so I'll take a look tomorrow.

:+1:

**Comment by dsavineau** [comment]
@goldyfruit See https://github.com/uoi-io/ansible-haproxy/pull/28

**Comment by goldyfruit** [comment]
@Sturlik @dsavineau thanks :)

**Pull request merged**
