### PR TITLE
add support for custom package name

### PR DESCRIPTION
**Pull request by pugnacity**
this could be useful when using HAProxy Enterprise

### CODE REVIEW

**Review by dsavineau — CHANGES_REQUESTED** [review]
I think there's not only the package name that should be change according to the documentation but also the service name and the directory path

https://www.haproxy.com/documentation/hapee/1-7r1/installation/centos-7/

**Comment by goldyfruit** [comment]
> I think there's not only the package name that should be change according to the documentation but also the service name and the directory path
> 
> https://www.haproxy.com/documentation/hapee/1-7r1/installation/centos-7/

:+1:

**Comment by goldyfruit** [comment]
@pugnacity any plan to continue this PR?

**Comment by pugnacity** [comment]
unfortunately we went with the open source version, so there is no need for us to continue the work. Sorry

**Pull request closed without merging**
